# Generated by Django 5.2.7 on 2025-10-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='assigned_courses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
