# Generated by Django 5.2.7 on 2025-10-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_faculty_assigned_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seats_available',
            field=models.IntegerField(default=0),
        ),
    ]
