# Generated by Django 5.2.7 on 2025-10-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_course_seats_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_seats',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='seats_available',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
