# Generated by Django 5.2.7 on 2025-10-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_course_total_seats_alter_course_seats_available'),
    ]

    operations = [
    ]
