# Generated by Django 5.2.7 on 2025-10-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20251025_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mode_of_entry',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Lateral', 'Lateral')], default='Regular', max_length=20),
        ),
    ]
